version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./uav_missions.db
    volumes:
      - ./backend:/app
      - ./ml:/app/ml
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm start
    depends_on:
      - backend

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=uav_missions
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ml-training:
    build: ./backend
    volumes:
      - ./ml:/app/ml
      - ./backend:/app
    command: python ml/train_model.py
    depends_on:
      - db

volumes:
  postgres_data:
